Sayılardan oluşan bir boyutlu array oluşturulur. 
Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [2]:
import numpy as np

In [3]:
sayilar = np.array([1, 2, 3, 4, 5], dtype=int)

In [4]:
boyut = sayilar.shape
print("Array Boyutu:", boyut)

Array Boyutu: (5,)


In [5]:
eleman_sayisi = sayilar.size
print("Eleman Sayısı:", eleman_sayisi)

Eleman Sayısı: 5


In [17]:
bir_boyutlu = np.array([1, 2, 3, 4, 5])

iki_boyutlu = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

uc_boyutlu = np.array([[[1, 2],
                       [3, 4],
                       [5, 6]],
                      [[7, 8],
                       [9, 10],
                       [11, 12]]])


In [18]:
boyut_iki = iki_boyutlu.shape
print("İki Boyutlu Array Boyutu:", boyut_iki)

İki Boyutlu Array Boyutu: (3, 4)


In [19]:
boyut_uc = uc_boyutlu.shape
print("Üç Boyutlu Array Boyutu:", boyut_uc)

Üç Boyutlu Array Boyutu: (2, 3, 2)


In [20]:
eleman_sayisi_iki = iki_boyutlu.size
print("İki Boyutlu Array Eleman Sayısı:", eleman_sayisi_iki)

İki Boyutlu Array Eleman Sayısı: 12


In [21]:
eleman_sayisi_uc = uc_boyutlu.size
print("Üç Boyutlu Array Eleman Sayısı:", eleman_sayisi_uc)

Üç Boyutlu Array Eleman Sayısı: 12


In [22]:
eleman = iki_boyutlu[1, 2]
print("Eleman:", eleman)

Eleman: 7


In [23]:
satir = iki_boyutlu[1, :]
print("Satır:", satir)

Satır: [5 6 7 8]


In [24]:
sutun = iki_boyutlu[:, 3]
print("Sütun:", sutun)

Sütun: [ 4  8 12]


In [25]:
eleman_uc = uc_boyutlu[1, 2, 1]
print("Üç Boyutlu Eleman:", eleman_uc)

Üç Boyutlu Eleman: 12


In [26]:
katman = uc_boyutlu[0, :, :]
print("Üç Boyutlu Katman:", katman)

Üç Boyutlu Katman: [[1 2]
 [3 4]
 [5 6]]


In [27]:
array1 = np.zeros((2, 3), dtype=int)
print("Sıfırlar Array:\n", array1)

Sıfırlar Array:
 [[0 0 0]
 [0 0 0]]


In [28]:
array2 = np.ones((2, 3), dtype=int)
print("Birler Array:\n", array2)

Birler Array:
 [[1 1 1]
 [1 1 1]]


In [29]:
birlesik_satir = np.vstack((array1, array2))
print("Satır Bazında Birleştirilmiş Array:\n", birlesik_satir)

Satır Bazında Birleştirilmiş Array:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [30]:
birlesik_sutun = np.hstack((array1, array2))
print("Sütun Bazında Birleştirilmiş Array:\n", birlesik_sutun)

Sütun Bazında Birleştirilmiş Array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
